# Netlify configuration file

[build]
  publish = "/"
  command = ""  # No build command needed for static site

# Redirects and headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "16"

# Site settings
[build.processing]
  skip_processing = false
